# Default callbacks configuration

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.ckpt_dir}
  filename: "epoch={epoch:03d}-loss={val/loss:.4f}"
  monitor: "val/loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  auto_insert_metric_name: false
  verbose: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/loss"
  mode: "min"
  patience: 20
  min_delta: 0.0
  verbose: false

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"

rich_progress:
  _target_: lightning.pytorch.callbacks.RichProgressBar
