# Hydra configuration

defaults:
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  # Output directory
  run:
    dir: ${paths.output_dir}/runs/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    dir: ${paths.output_dir}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  job:
    # Change working directory to output dir
    chdir: false

  # Verbose mode
  verbose: false
