# Hydra configuration (this file is the hydra package; keys are top-level)
# https://hydra.cc/docs/configure_hydra/intro/

defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# Output directory
run:
  dir: ${paths.output_dir}/runs/${now:%Y-%m-%d_%H-%M-%S}

sweep:
  dir: ${paths.output_dir}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

# Do not change cwd to output dir
job:
  chdir: false

verbose: false
